title: Tzu-Ruei Yang, PhD
description: 古生物學家的研究日誌
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0

# 這是新加入的導航選單設定
header_pages:
  - about.md
  - publications.md
  - research.md
  - media.md
  - contact.md
